#!/bin/zsh

function mmd5 (){
if [ $# -ne 1 ] ; then
    dir=$1
    pic=$2
else
    dir=/opt/home/twittoru/wallpaper
    pic="$1"
fi

    ext=$(gm identify -format "%m" "$pic""[0]" | tr "[A-Z]" "[a-z]")
    md5sum=$(md5 -q "$pic")
    target=$dir/$(echo $md5sum | head -c 2| sed -e 's/./&\//')/$md5sum"."$ext
    touch $target
    cp "$pic" $target
    rm "$pic"
}

function mmd5single (){
    dir=$1
    pic=$2
    ext=$(gm identify -format "%m" "$pic""[0]" | tr "[A-Z]" "[a-z]")
    md5sum=$(md5 -q "$pic")
    target=$dir/$md5sum"."$ext
    #touch $target
    #cp "$pic" $target
    #rm "$pic"
    mv "$pic" $target
}
